### ISSUE TITLE
[documentation] the git hook described on sismo.sensiolabs.org doesn't work

### ISSUE THREAD

**Issue by axiac** [FriendsOfPHP/Sismo#133] opened 2016-04-26 20:59 UTC
There are two issues on the Git hook described on sismo.sensiolabs.org:
1. the backticks are escaped and they shouldn't be; because of that they land as literal backticks in the command line and Sismo complains about invalid number of arguments and doesn't run;
2. (after removing the escape of the backticks) the Git hook works fine with the command line git but it makes Git GUI programs wait until Sismo completes the build. I only tested with Atlassian SourceTree on OSX but the cause of this behaviour (the stdout and stderr are not closed or redirected) could affect other Git GUI clients as well.

The Git hook presented in `README.rst` does not expose any of these problems. I think it would be great if you copy it into the http://sismo.sensiolabs.org page.

**Comment by lyrixx** [comment] 2016-04-27 10:04
Thanks for this feedback.

Could you open a PR to fix that?

Thanks.

**Comment by axiac** [comment] 2016-04-27 19:43
I would gladly open a PR to fix the issue but I cannot. The problem is not in the code or the documentation located in this repository but on the web page http://sismo.sensiolabs.org.

I discovered now that the same problem was reported three years ago by pull request #92. That pull request fixed the problem in `README.rst` but the page at http://sismo.sensiolabs.org still displays the wrong Git hook.

**Comment by lyrixx** [comment] 2016-04-27 23:34
@fabpot : could you re deploy the website ? Thanks !

**Comment by naitsirch** [comment] 2017-01-16 16:48
Same problem here. If one executes
```bash
php /usr/local/bin/sismo.php build hdo-futar \`git log -1 HEAD --pretty="%H"\`
```
As it is shown in the doku, one will get this error:

> [RuntimeException]   
> Too many arguments.

The problem is, that this error is not shown if the script is executed as git hook. This makes it hard to find the error :-(

**Comment by fabpot** [comment] 2017-06-08 23:44
fixed now

**Closed by fabpot** 2017-06-08 23:44 UTC
